---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: f76ec4a2b0360b92a3e74dd964cd532342a3483a
  local-dir: dist
